#pragma once
#define M1_NOTCHES {16}
#define M1_ROTOR "EKMFLGDQVZNTOWYHXUSPAIBRCJ"
#define M2_NOTCHES {4}
#define M2_ROTOR "AJDKSIRUXBLHWTMCQGZNPYFVOE"
#define M3_NOTCHES {21}
#define M3_ROTOR "BDFHJLCPRTXVZNYEIWGAKMUSQO"
#define M4_NOTCHES {9}
#define M4_ROTOR "ESOVPZJAYQUIRHXLNFTGKDCMWB"
#define M5_NOTCHES {25}
#define M5_ROTOR "VZBRGITYUPSDNHLXAWMJQOFECK"
#define M6_NOTCHES {12, 25}
#define M6_ROTOR "JPGVOUMFYQBENHZRDKASXLICTW"
#define M7_NOTCHES {12, 25}
#define M7_ROTOR "NZJHGRCXMYSWBOUFAIVLPEKQDT"
#define M8_NOTCHES {12, 25}
#define M8_ROTOR "FKQHTLXOCBJSPDZRAMEWNIUYGV"